dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - LARAVEL=^6.0
    - LARAVEL=^7.0

matrix:
  fast_finish: true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script: composer test
